//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESO_VEHICULO()
        {
            this.REPARACIONs = new HashSet<REPARACION>();
        }
    
        public int ID_INGRESO { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string DPI { get; set; }
        public string T_CARRO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string PLACA { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string NOMBRE_TALLER { get; set; }
        public string DESCRIP_PROBLEMA { get; set; }
    
        public virtual TALLER TALLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPARACION> REPARACIONs { get; set; }
    }
}
