//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carrosEntities : DbContext
    {
        public carrosEntities()
            : base("name=carrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<INGRESO_VEHICULO> INGRESO_VEHICULO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<REPARACION> REPARACION { get; set; }
        public virtual DbSet<REPUESTO> REPUESTO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TALLER> TALLER { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
