//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUTOMOTRIZEntities1 : DbContext
    {
        public AUTOMOTRIZEntities1()
            : base("name=AUTOMOTRIZEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<INGRESO_VEHICULO> INGRESO_VEHICULO { get; set; }
        public virtual DbSet<REPARACION> REPARACIONs { get; set; }
        public virtual DbSet<REPUESTO> REPUESTOes { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOs { get; set; }
        public virtual DbSet<TALLER> TALLERs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
